version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: isedevdb
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: localdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
